version: '3.8'

services:
  app:
    build:
      context: ./backend
    container_name: laravel_app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./backend:/var/www
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
    container_name: vue_frontend
    restart: unless-stopped
    tty: true
    ports:
      - "8080:8080"
    networks:
      - app-network

  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - app-network

  redis:
    image: redis:alpine
    container_name: redis
    restart: unless-stopped
    tty: true
    ports:
      - "6379:6379"
    networks:
      - app-network

  minio:
    image: minio/minio
    container_name: minio
    restart: unless-stopped
    tty: true
    ports:
      - "9001:9000"
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server /data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge